@startuml heis_tilstandsdiagram
title "Tilstandsdiagram for heis__kontroller__"

state "Normal operasjon" as normal
state "Oppstart" as oppstart
state "Normal nødstopp" as normal_stoppet
state "Oppstarts nødstopp" as oppstart_stoppet
'state "Forvirret" as forvirret

state normal {
  state "Bevegelse" as bevegelse
  state "Klar" as klar 
  state "Betjening" as betjening

  [*] --> klar

  klar -down-> bevegelse: Mottar bestilling\nfor etasje N
  klar: Klar i kjent tillstand\nfor å ta bestilling.
  klar: Beveger seg ikke.
  
  bevegelse --> bevegelse: Mottar ny bestilling\nfor etasje N
  bevegelse -up-> betjening: Treffer\netasje N
  bevegelse: Beveger seg til\nbestilt etasje N.

  betjening -left-> klar: 3 sekunder har gått\nog ingen obstruksjon
  betjening: Betjener etasje N.
  betjening: Døren er åpen.
  
  normal --> normal_stoppet: Stoppknapp\ntrykkes
'normal --> forvirret: Treffer\nuforventet\netasje
}

[*] --> oppstart

oppstart --> normal: Treffer\netasje N
oppstart -right-> oppstart_stoppet: Stoppknapp\ntrykkes
oppstart: Beveger seg\n__forsiktig__ nedover.

oppstart_stoppet -left-> oppstart: Stoppknapp\nslippes
oppstart_stoppet: Stoppet i ukjent tilstand.

normal_stoppet --> normal: Stoppknapp\nslippes\nog 3 sekunder\nhar gått
normal_stoppet: Stoppet i vilkårlig tilstand.
normal_stoppet: Dør åpen hvis i en etasje.

@enduml
