@startuml heis_tilstandsdiagram
title "Tilstandsdiagram for FSM"

state "Normal operasjon" as normal
state "Oppstart" as oppstart
state "Nødstopp" as stoppet
'state "Oppstarts nødstopp" as oppstart_stoppet
'state "Forvirret" as forvirret

state normal {
state "Bevegelse" as bevegelse
state "Stanset" as stanset 
'state "Betjening" as betjening

  [*] --> stanset

  stanset --> bevegelse: Mottar bestilling\n[dør lukket]\n
'stanset --> stoppet: Stoppknapp trykkes
  stanset --> stanset: 3 sekunder har gått\n[dør åpen og ingen obstruksjon]\n / dør lukkes
  stanset: Klar i kjent tillstand\nfor å ta bestilling.
  stanset: Beveger seg ikke.
  
  bevegelse --> bevegelse: Mottar bestilling
'bevegelse --> stoppet: Stoppknapp trykkes
  bevegelse -up-> stanset: Treffer etasje N\n/ åpne dør
'bevegelse -up-> betjening: Treffer\netasje N
  bevegelse: Beveger seg til\nbestilt etasje N.

'betjening -left-> klar: 3 sekunder har gått\nog ingen obstruksjon
'betjening: Betjener etasje N.
'betjening: Døren er åpen.
  
  normal --> stoppet: Stoppknapp inne\n[i etasje]\n / åpne dør
  normal -left-> stoppet: Stoppknapp inne\n[utenfor etasje]
'normal --> forvirret: Treffer\nuforventet\netasje
}

[*] -down-> oppstart

oppstart -down-> normal: Treffer etasje N
oppstart -right-> stoppet: Stoppknapp inne
oppstart: Beveger seg\nnedover.

'oppstart_stoppet -left-> oppstart: Stoppknapp\nslippes
'oppstart_stoppet: Stoppet i ukjent tilstand.

stoppet --> normal: Stoppknapp ute\n[kjent tilstand]
stoppet -left-> oppstart: Stoppknapp ute\n[ukjent tilstand]
stoppet: Stoppet i vilkårlig tilstand.
stoppet: Blokkerer og sletter bestillnger.

@enduml
